service: asure-employee-import${opt:branchName, ''}

provider:
  stage: ${file(${self:custom.configFile}):stage}
  name: aws
  runtime: nodejs16.x
  timeout: 900   # AWS API Gateway timeout limit (30s)
  versionFunctions: false
  memorySize: 1024
  logRetentionInDays: ${file(${self:custom.configFile}):logRetentionInDays}

  environment:  #environment variables
    awsRegion: ${file(${self:custom.configFile}):awsRegion}
    secretsAwsEndPoint: ${file(${self:custom.configFile}):secretsAwsEndPoint}
    apiSecretId: ${file(${self:custom.configFile}):apiSecretId}
    rdsCredentialsId: ${file(${self:custom.configFile}):rdsCredentialsId}
    payrollApiCredentialsId: ${file(${self:custom.configFile}):payrollApiCredentialsId}
    ssoCredentialsId: ${file(${self:custom.configFile}):ssoCredentialsId}
    asureAdminRoleId: ${file(${self:custom.configFile}):asureAdminRoleId}
    evoHrGlobalAdmin: ${file(${self:custom.configFile}):evoHrGlobalAdmin}
    stage: ${file(${self:custom.configFile}):stage}
    apiDomain: ${file(${self:custom.configFile}):apiDomain}
    domain: ${file(${self:custom.configFile}):domain}
    hrServicesDomain: ${file(${self:custom.configFile}):hrServicesDomain}
    hrDatabaseCreatorStateMachineArn: arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrDatabaseCreator-${self:provider.stage}
    hrCompanyMigratorStateMachineArn: arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrCompanyMigrator-${self:provider.stage}
    hrEmployeeImportStateMachineArn: arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrEmployeeImportStateMachine-${self:provider.stage}
    teamNotificationTopicArn: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:mojojojo-status-notification
    scopeBaseDomain: ${file(${self:custom.configFile}):scopeBaseDomain}
    goldilocksApplicationId: ${file(${self:custom.configFile}):goldilocksApplicationId}
    hrApplicationId: ${file(${self:custom.configFile}):hrApplicationId}
    ssoPublicKey1: ${file(${self:custom.configFile}):ssoPublicKey1}
    ssoPublicKey2: ${file(${self:custom.configFile}):ssoPublicKey2}
    pageLimitDefault: 30
    pageLimitMax: 100
    AuditLogGroupName: ${file(${self:custom.configFile}):AuditLogGroupName}
    tenantAdminCredentialsId: ${file(${self:custom.configFile}):tenantAdminCredentialsId}
    goldilocksTenantId: ${file(${self:custom.configFile}):goldilocksTenantId}
    integrationId: ${file(${self:custom.configFile}):integrationId}
    eSignatureApiCredentialsId: ${file(${self:custom.configFile}):eSignatureApiCredentialsId}
    tlmReadRole: ${file(${self:custom.configFile}):tlmReadRole}
    tlmWriteRole: ${file(${self:custom.configFile}):tlmWriteRole}
    fileBucketName: ${file(${self:custom.configFile}):fileBucketName}
    employeeImportBucketName: ${file(${self:custom.configFile}):employeeImportBucketName}
    payrollBaseUrl: ${file(${self:custom.configFile}):payrollBaseUrl}
    dbBackupBucket: ${file(${self:custom.configFile}):dbBackupBucket}

  iamRoleStatements:
    - Effect: Allow
      Action: # Gives permission to create the necessary ENIs for execution in VPC
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
        - ec2:DetachNetworkInterface
      Resource: "arn:aws:ec2:us-east-1:*:*"

    - Effect: Allow
      Action:
        - secretsmanager:*
        - kms:DescribeKey
        - kms:ListAliases
        - kms:ListKeys
      Resource: "*"

    - Effect: Allow
      Action:
        - acm:ListCertificates
        - apigateway:GET
        - apigateway:DELETE
        - apigateway:POST
        - apigateway:PATCH
        - apigateway:PUT
        - cloudfront:UpdateDistribution
        - route53:ListHostedZones
        - route53:GetHostedZone
        - route53:ListResourceRecordSets
      Resource: "*"

    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

    - Effect: Allow
      Action:
        - rds:DescribeDBInstances
      Resource: "*"

    - Effect: Allow
      Action: states:StartExecution
      Resource:
        - "arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrDatabaseCreator${opt:branchName, ''}-${self:provider.stage}"
        - "arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrCompanyMigrator${opt:branchName, ''}-${self:provider.stage}"
        - "arn:aws:states:${self:provider.region}:#{AWS::AccountId}:stateMachine:HrEmployeeImportStateMachine${opt:branchName, ''}-${self:provider.stage}"

    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:GetObjectAcl
        - s3:GetBucket
        - s3:ListBucket
        - s3:PutObject
        - s3:DeleteObject
      Resource: "arn:aws:s3:::*"

    - Effect: Allow
      Action:
        - sns:Publish
      Resource: arn:aws:sns:${self:provider.region}:#{AWS::AccountId}:mojojojo-status-notification

    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:PutItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:table/ConnectionStrings"
      
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource: arn:aws:dynamodb:us-east-1:*:table/ConnectionStrings/index/*
    
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  getDataImportTypes:
    handler: src/handler.getDataImportTypes
    events:
        - http:
            path: /tenants/{tenantId}/data-import-types
            method: get
            cors:
              origin: '*'

  getDataImportEvent:
    handler: src/handler.getDataImportEvent
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-imports
            method: get
            cors:
              origin: '*'

  getDataImportEventByType:
    handler: src/handler.getDataImportEventByType
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-import-types/{dataImportTypeId}/data-imports
            method: get
            cors:
              origin: '*'

  getDataImportEventDetails:
    handler: src/handler.getDataImportEventDetails
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-imports/{dataImportId}/data-import-details
            method: get
            cors:
              origin: '*'

  downloadImportData:
    handler: src/handler.downloadImportData
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-imports/{dataImportId}/download
            method: get
            cors:
              origin: '*'

  getTemplate:
    handler: src/handler.getTemplate
    events:
        - http:
            path: /tenants/{tenantId}/data-import-types/{dataImportTypeId}/template
            method: get
            cors:
              origin: '*'
  
  uploadUrl:
    handler: src/handler.uploadUrl
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-imports/upload-url
            method: post
            cors:
              origin: '*'

  dataImports:
    handler: src/handler.dataImports
    events:
        - http:
            path: /tenants/{tenantId}/companies/{companyId}/data-imports
            method: post
            cors:
              origin: '*'

  setProcessingStatusGlobal:
    handler: src/handler.setProcessingStatusGlobal
    memorySize: 1024

  setCompletedStatusGlobal:
    handler: src/handler.setCompletedStatusGlobal
    memorySize: 1024

  setFailedStatusGlobal:
    handler: src/handler.setFailedStatusGlobal
    memorySize: 1024

  updateEmployee:
    handler: src/handler.updateEmployee
    memorySize: 1024

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-plugin-warmup
  - serverless-webpack
  - serverless-aws-documentation
  - serverless-cloudformation-resource-counter
  - serverless-domain-manager
  - serverless-pseudo-parameters
  - serverless-offline

package:
  individually: false
  excludeDevDependencies: true

custom:
  configFile: ../../${opt:variables, 'local'}.serverless.variables.json
  warmup:
    timeout: 60
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
    default:
        - production
        - development
        - staging
    concurrency: 3
  webpack:
    webpackConfig: ./webpack/${file(${self:custom.configFile}):webpackConfigurationFile}
    includeModules: true
    packager: 'npm'
  customDomain:
    basePath: employee-import${opt:branchName, ''}
    domainName: hr-services.${file(${self:custom.configFile}):domain}
    certificateArn: '*.${file(${self:custom.configFile}):domainCertificateArn}'
    createRoute53Record: false
