export const tenantId = 'e5a19feb-0fca-4b61-9b7a-43a2a6dd7414';
export const companyId = '3';
export const anotherCompanyId = '444';
export const companyIdWithCharacter = '3abc';
export const domainName = 'https://test.evolution-software.com';
export const path = '/applicant-tracking/development/tenants/e5a19feb-0fca-4b61-9b7a-43a2a6dd7414';
export const unsupportedQueryParam = '&unsupportedParam=nothing';
export const undefinedValue = undefined;
export const userEmail = 'mypersonalemail@abc.com';