
service: asure-encryption


provider:
  stage: ${file(${self:custom.configFile}):stage}
  name: aws
  runtime: dotnetcore2.1
  timeout: 60
  versionFunctions: false
  memorySize: 256
  logRetentionInDays: ${file(${self:custom.configFile}):logRetentionInDays}
  
  environment:  #environment variables
    awsRegion: ${file(${self:custom.configFile}):awsRegion}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:*
        - kms:DescribeKey
        - kms:ListAliases
        - kms:ListKeys
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

package:
  individually: true

functions:
  decrypt:
    handler: Asure.HR.Encryption::Encryption.Handler::Decrypt

    package:
      artifact: asure.encryption.zip

plugins:
  - serverless-plugin-warmup
custom:
  configFile: ../${opt:variables, 'local'}.serverless.variables.json
  warmup:
    timeout: 60
    schedule: 'cron(0/5 * * * ? *)'    # Run every 5 minutes
    default:
        - production
        - development
        - staging
    concurrency: 3
